name: SwagSMPCore
version: '1.0-SNAPSHOT'
main: com.beauver.swagsmp.SwagSMPCore
api-version: '1.20'
authors: [ Beauver ]
description: A plugin for the Minecraft Server SwagSMP
website: https://beauver.com/
